# Generated by Django 3.2.16 on 2023-01-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=11, verbose_name='name')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email')),
            ],
        ),
    ]
