# Generated by Django 2.2.12 on 2023-01-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'bk', 'verbose_name_plural': 'bk'},
        ),
    ]
